# v.1.0.37
version: '3.7'
services:
  backend:
    image: {{ env.IMAGE_URL }}
    container_name: backend-core
    networks:
      - internet
    env_file:
      - /data/.env
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - minio
    restart: unless-stopped


  tools-backend:
    image: cr.yandex/crpfap56bqr8nkph7d9g/tools-backend:latest
    container_name: tools-backend
    networks:
      - internet
    env_file:
      - /data/.env
    ports:
      - 3400:3000
    depends_on:
      - postgres
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.49.1
    ports:
      - 9090:9090
    networks:
      - internet
    volumes:
      - /data/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    container_name: prometheus
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD-SHELL", "wget -q --tries=1 -O- http://localhost:9090/-/ready || exit 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5


  postgres:
    image: postgres:13.2-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - /postgresdata:/var/lib/postgresql/data
      - /migrations/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
    restart: always
    env_file:
      - /data/.env
    networks:
      - internet

  pgadmin:
    image: dpage/pgadmin4:4.18
    container_name: pgadmin-4
    restart: always
    env_file:
      - /data/.env
    ports:
      - 8080:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - internet

  minio:
    image: cr.yandex/crpfap56bqr8nkph7d9g/minio:2024.11.7
    container_name: minio
    restart: always
    env_file:
      - /data/.env
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - minio-data:/bitnami/minio/data
    networks:
      - internet

  loki:
    image: grafana/loki:latest
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki
    networks:
      - internet
    healthcheck:
      test: ["CMD-SHELL", "wget -q --tries=1 -O- http://localhost:3100/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3200:3000
    env_file:
      - /data/.env
    depends_on:
      - loki
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - internet
    healthcheck:
      test: ["CMD-SHELL", "wget -q --tries=1 -O- http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  frontend:
    image: cr.yandex/crpfap56bqr8nkph7d9g/front-places:latest
    ports:
      - 3005:80
    depends_on:
      - backend
    networks:
      - internet
    restart: unless-stopped

  tools-frontend:
    image: cr.yandex/crpfap56bqr8nkph7d9g/tools-frontend:latest
    ports:
      - 3405:80
    depends_on:
      - tools-backend
    networks:
      - internet
    restart: unless-stopped

  ntlstl:
    image: cr.yandex/crpfap56bqr8nkph7d9g/ntlstl:latest
    platform: linux/amd64
    ports:
      - 3505:3000
    networks:
      - internet
    environment:
      - NODE_ENV=production
    restart: unless-stopped


  notes-core:
    image: cr.yandex/crpfap56bqr8nkph7d9g/notes-core:latest
    container_name: notes-core
    networks:
      - internet
    env_file:
      - /data/.env
    ports:
      - 3450:3000
    depends_on:
      - postgres
    restart: unless-stopped

  notes-client:
    image: cr.yandex/crpfap56bqr8nkph7d9g/notes-client:latest
    ports:
      - 3455:80
    depends_on:
      - notes-core
    networks:
      - internet
    restart: unless-stopped

  

  # chromadb:
  #   image: chromadb/chroma:latest
  #   container_name: chromadb
  #   restart: always
  #   ports:
  #     - "8001:8000"
  #   volumes:
  #     - ./chromadata:/chroma/chroma
  #   environment:
  #     IS_PERSISTENT: "TRUE"
  #     ANONYMIZED_TELEMETRY: "FALSE"
  #   networks:
  #     - internal-network
  #     - internet


volumes:
  postgresdata:
    driver: local
  pgadmin-data:
    driver: local
  minio-data:
    driver: local
  loki_data:
  grafana_data:
  prometheus-data:
    driver: local

networks:
  internal-network:
    driver: bridge
    internal: true
  internet:
    driver: bridge
